#  Approved for public release: distribution is unlimited. PA Case Number AFRL-2023-4617.

#  © 2023 Raytheon BBN Technologies Corp. All rights reserved. Sponsored by the Air Force Research Laboratory (AFRL)  



version: '3'
services:
  mace:
    # build: .
    image: mace
    container_name: mace
    cap_add:
      - SYS_TIME
    ports:
      - 123:123
      - 123:123/udp
      - 1883:1883
      - 5000:5000
      - 9091:9091
      - 11310:11310
      - 11312:11312
      - 11313:11313
    expose: [11310, 11312, 11313]
    entrypoint: ./scripts/docker/start_all.sh
    # Edit number of sim entities below: [Quads, Rovers, Targets]
    command: ["1", "1", "4"]
    # network_mode: 'host'
